version: "3.8"

services:

  nacos:
    image: nacos/nacos-server
    container_name: nacos-container
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
    restart: always

  minio:
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    container_name: minio-container
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    command: server /data
    ports:
      - "9000:9000"
    restart: always
